services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homeserver:3000
    volumes:
      - ./config:/app/config
    extra_hosts:
      - "homeserver:host-gateway"
    restart: unless-stopped
